<?php

use Illuminate\Database\Seeder;

class AcnhWordsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      //DBのクリア
      DB::table('words')->truncate();

      $words = [
          $words1 = [
            'word_sentence' => 'たぬき開発の客',
            'word_right' => '客',
            'word_left' => 'たぬき開発の',
            'get_method' => '島へようこそ！',
            'get_sentence' => '無人島移住パッケージプランに申し込む',
          ],
          $words2 = [
            'word_sentence' => '卒業したてのボウズ',
            'word_right' => 'ボウズ',
            'word_left' => '卒業したての',
            'get_method' => '目指せ、釣り名人',
            'get_sentence' => 'サカナを10ぴき釣る',
          ],
          $words3 = [
            'word_sentence' => 'いっぱしの釣り好き',
            'word_right' => '釣り好き',
            'word_left' => 'いっぱしの',
            'get_method' => '目指せ、釣り名人',
            'get_sentence' => 'サカナを100ぴき釣る',
          ],
          $words4 = [
            'word_sentence' => 'それなりのビーチボーイ、ビーチガール',
            'word_right' => 'ビーチボーイ、ビーチガール',
            'word_left' => 'それなりの',
            'get_method' => '目指せ、釣り名人',
            'get_sentence' => 'サカナを500ぴき釣る',
          ],
          $words5 = [
            'word_sentence' => '雑魚のサカナ好き',
            'word_right' => 'サカナ好き',
            'word_left' => '雑魚の',
            'get_method' => 'サカナ博士になろう',
            'get_sentence' => 'サカナ図鑑を10個うめる',
          ],
          $words6 = [
            'word_sentence' => 'ピチピチの釣り師',
            'word_right' => '釣り師',
            'word_left' => 'ピチピチの',
            'get_method' => 'サカナ博士になろう',
            'get_sentence' => 'サカナ図鑑を20個うめる',
          ],
          $words6 = [
            'word_sentence' => '養殖の熱帯魚',
            'word_right' => '熱帯魚',
            'word_left' => '養殖の',
            'get_method' => 'サカナ博士になろう',
            'get_sentence' => 'サカナ図鑑を40個うめる',
          ],
          $words7 = [
            'word_sentence' => 'まだまだシャイ',
            'word_right' => 'シャイ',
            'word_left' => 'まだまだ',
            'get_method' => '全ての基本はあいさつから！',
            'get_sentence' => '1日で島民全員に声をかける',
          ],
          $words8 = [
            'word_sentence' => 'うまれたてのたまご',
            'word_right' => 'たまご',
            'word_left' => 'うまれたての',
            'get_method' => '昆虫ハンターへの道！',
            'get_sentence' => 'ムシを10匹つかまえる',
          ],
          $words9 = [
            'word_sentence' => '最弱の幼虫',
            'word_right' => '幼虫',
            'word_left' => '最弱の',
            'get_method' => '昆虫ハンターへの道！',
            'get_sentence' => 'ムシを100匹つかまえる',
          ],
          $words10 = [
            'word_sentence' => '一皮むけそうなサナギ',
            'word_right' => 'サナギ',
            'word_left' => '一皮むけそうな',
            'get_method' => '昆虫ハンターへの道！',
            'get_sentence' => 'ムシを500匹つかまえる',
          ],
          $words11 = [
            'word_sentence' => '趣味程度のムシ好き',
            'word_right' => 'ムシ好き',
            'word_left' => '趣味程度の',
            'get_method' => '昆虫博士になれるかな？',
            'get_sentence' => 'いきもの図鑑のムシページを10個うめる',
          ],
          $words12 = [
            'word_sentence' => '夜行性のムシ',
            'word_right' => 'ムシ',
            'word_left' => '夜行性の',
            'get_method' => '昆虫博士になれるかな？',
            'get_sentence' => 'いきもの図鑑のムシページを20個うめる',
          ],
          $words13 = [
            'word_sentence' => 'アリよりのアリ',
            'word_right' => 'アリ',
            'word_left' => 'アリよりの',
            'get_method' => '昆虫博士になれるかな？！',
            'get_sentence' => 'いきもの図鑑のムシページを40個うめる',
          ],
          $words14 = [
            'word_sentence' => '雑学の代表',
            'word_right' => '代表',
            'word_left' => '雑学の',
            'get_method' => 'DIYのレシピを増やそう',
            'get_sentence' => 'DIYのレシピを10個集める',
          ],
          $words15 = [
            'word_sentence' => '物知りな知識人',
            'word_right' => '知識人',
            'word_left' => '物知りな',
            'get_method' => 'DIYのレシピを増やそう',
            'get_sentence' => 'DIYのレシピを50個集める',
          ],
          $words16 = [
            'word_sentence' => '控えめに言って有識者',
            'word_right' => '有識者',
            'word_left' => '控えめに言って',
            'get_method' => 'DIYのレシピを増やそう',
            'get_sentence' => 'DIYのレシピを100個集める',
          ],
          $words17 = [
            'word_sentence' => '知識欲の虜',
            'word_right' => '虜',
            'word_left' => '知識欲の',
            'get_method' => 'DIYのレシピを増やそう',
            'get_sentence' => 'DIYのレシピを150個集める',
          ],
          $words18 = [
            'word_sentence' => 'ものづくりの愛好家',
            'word_right' => '愛好家',
            'word_left' => 'ものづくりの',
            'get_method' => '暮らしの基本は道具作りから',
            'get_sentence' => 'どうぐを5回つくる',
          ],
          $words19 = [
            'word_sentence' => 'クラフト系の部員',
            'word_right' => '部員',
            'word_left' => 'クラフト系の',
            'get_method' => '暮らしの基本は道具作りから',
            'get_sentence' => 'どうぐを50回つくる',
          ],
          $words20 = [
            'word_sentence' => 'イケてるスペシャリスト',
            'word_right' => 'スペシャリスト',
            'word_left' => 'イケてる',
            'get_method' => '暮らしの基本は道具作りから',
            'get_sentence' => 'どうぐを200回つくる',
          ],
          $words21 = [
            'word_sentence' => '半人前の職人',
            'word_right' => '職人',
            'word_left' => '半人前の',
            'get_method' => '手作り家具で 暮らしを豊かに',
            'get_sentence' => 'ごめんなさい！調査中です！',
          ],
          $words22 = [
            'word_sentence' => 'オンリーワンの変わり者',
            'word_right' => '変わり者',
            'word_left' => 'オンリーワンの',
            'get_method' => 'リメイクの達人になろう！',
            'get_sentence' => 'リメイクを5回おこなう',
          ],
          $words23 = [
            'word_sentence' => '某・プロデューサー',
            'word_right' => 'プロデューサー',
            'word_left' => '某・',
            'get_method' => '森のウッドカッター！',
            'get_sentence' => '木材を20回切り出す',
          ],
          $words24 = [
            'word_sentence' => '切れ味のいいソルジャー',
            'word_right' => 'ソルジャー',
            'word_left' => '切れ味のいい',
            'get_method' => '森のウッドカッター！',
            'get_sentence' => '木材を500回切り出す',
          ],
          $words25 = [
            'word_sentence' => 'ヤンチャなお調子者',
            'word_right' => 'お調子者',
            'word_left' => 'ヤンチャな',
            'get_method' => '道具クラッシャー！',
            'get_sentence' => 'どうぐを1回こわす',
          ],
          $words26 = [
            'word_sentence' => '勢いあまったクラッシャー',
            'word_right' => 'クラッシャー',
            'word_left' => '勢いあまった',
            'get_method' => '道具クラッシャー！',
            'get_sentence' => 'どうぐを20回こわす',
          ],
          $words27 = [
            'word_sentence' => '暴れん坊なあらくれ者',
            'word_right' => 'あらくれ者',
            'word_left' => '暴れん坊な',
            'get_method' => '道具クラッシャー！',
            'get_sentence' => 'どうぐを50回こわす',
          ],
          $words28 = [
            'word_sentence' => '加減を知らないデストロイヤー',
            'word_right' => 'デストロイヤー',
            'word_left' => '加減を知らない',
            'get_method' => '道具クラッシャー！',
            'get_sentence' => 'どうぐを100回こわす',
          ],
          $words29 = [
            'word_sentence' => '体育会系の筋肉',
            'word_right' => '筋肉',
            'word_left' => '体育会系の',
            'get_method' => '岩たたきのプロだなも！',
            'get_sentence' => '8回連続で岩を叩く',
          ],
          $words30 = [
            'word_sentence' => '発掘された化石',
            'word_right' => '化石',
            'word_left' => '発掘された',
            'get_method' => 'かせき発掘人に認定だなも！',
            'get_sentence' => 'はじめて化石を発掘する',
          ],
          $words31 = [
            'word_sentence' => '名もなき何か',
            'word_right' => '何か',
            'word_left' => '名もなき',
            'get_method' => 'なんのかせきかな？！',
            'get_sentence' => 'かせきを5回鑑定してもらう',
          ],
          $words32 = [
            'word_sentence' => '古の真実',
            'word_right' => '真実',
            'word_left' => '古の',
            'get_method' => 'なんのかせきかな？！',
            'get_sentence' => 'かせきを30回鑑定してもらう',
          ],
          $words33 = [
            'word_sentence' => '歴史好きの知識人',
            'word_right' => '知識人',
            'word_left' => '歴史好きの',
            'get_method' => 'なんのかせきかな？！',
            'get_sentence' => 'かせきを100回鑑定してもらう',
          ],
          $words34 = [
            'word_sentence' => '雑食の掃除人',
            'word_right' => '掃除人',
            'word_left' => '雑食の',
            'get_method' => '草むしりボランティア募集',
            'get_sentence' => '200個雑草を引き取ってもらう',
          ],
            $words35 = [
            'word_sentence' => '草食系の仕掛人',
            'word_right' => '仕掛人',
            'word_left' => '草食系の',
            'get_method' => '草むしりボランティア募集',
            'get_sentence' => '1000個雑草を引き取ってもらう',
            ],
          $words35 = [
            'word_sentence' => 'ボーボーの雑草',
            'word_right' => '雑草',
            'word_left' => 'ボーボーの',
            'get_method' => '草むしりボランティア募集',
            'get_sentence' => '2000個雑草を引き取ってもらう',
          ],
          $words36 = [
            'word_sentence' => 'ワイルドな獣',
            'word_right' => '獣',
            'word_left' => 'ワイルドな',
            'get_method' => '草むしりボランティア募集',
            'get_sentence' => '3000個雑草を引き取ってもらう',
          ],
          $words37 = [
            'word_sentence' => '温室育ちの花',
            'word_right' => '花',
            'word_left' => '温室育ちの',
            'get_method' => 'エンジョイ・ガーデニング！',
            'get_sentence' => '自分の島に花や球根を10個植える',
          ],
          $words37 = [
            'word_sentence' => 'トゲのある薔薇',
            'word_right' => '薔薇',
            'word_left' => 'トゲのある',
            'get_method' => 'エンジョイ・ガーデニング！',
            'get_sentence' => '自分の島に花や球根を50個植える',
          ],
          $words38 = [
            'word_sentence' => '楽園の癒し',
            'word_right' => '癒し',
            'word_left' => '楽園の',
            'get_method' => 'エンジョイ・ガーデニング！',
            'get_sentence' => '自分の島に花や球根を100個植える',
          ],
          $words39 = [
            'word_sentence' => '粋なはからい',
            'word_right' => 'はからい',
            'word_left' => '粋な',
            'get_method' => '水やりで花のあるくらし',
            'get_sentence' => '水やりを10回おこなう',
          ],
          $words40 = [
            'word_sentence' => 'マメな世話好き',
            'word_right' => '世話好き',
            'word_left' => 'マメな',
            'get_method' => '水やりで花のあるくらし',
            'get_sentence' => '水やりを50回おこなう',
          ],
          $words41 = [
            'word_sentence' => '丁寧なガーデニング好き',
            'word_right' => 'ガーデニング好き',
            'word_left' => '丁寧な',
            'get_method' => '水やりで花のあるくらし',
            'get_sentence' => '水やりを100回おこなう',
          ],
          $words41 = [
            'word_sentence' => '世話好きの番長',
            'word_right' => '番長',
            'word_left' => '世話好きの',
            'get_method' => '水やりで花のあるくらし',
            'get_sentence' => '水やりを500回おこなう',
          ],
          $words42 = [
            'word_sentence' => '花を愛する大将（女将）',
            'word_right' => '大将（女将）',
            'word_left' => '花を愛する',
            'get_method' => '水やりで花のあるくらし',
            'get_sentence' => '水やりを1000回おこなう',
          ],
          $words43 = [
            'word_sentence' => '森の番人',
            'word_right' => '番人',
            'word_left' => '森の',
            'get_method' => '島に緑を！植樹チャレンジ！',
            'get_sentence' => '苗木を5回植林する',
          ],
          $words44 = [
            'word_sentence' => '未熟な関係',
            'word_right' => '関係',
            'word_left' => '未熟な',
            'get_method' => 'フルーツ狩りを楽しもう！',
          'get_sentence' => 'フルーツを20回売る',
          ],
          $words45 = [
            'word_sentence' => '早熟な実',
            'word_right' => '実',
            'word_left' => '早熟な',
            'get_method' => 'フルーツ狩りを楽しもう！',
            'get_sentence' => 'フルーツを100回売る',
          ],
          $words45 = [
            'word_sentence' => '旬の果実',
            'word_right' => '果実',
            'word_left' => '旬の',
            'get_method' => 'フルーツ狩りを楽しもう！',
            'get_sentence' => 'フルーツを500回売る',
          ],
          $words46 = [
            'word_sentence' => '双子のかたわれ',
            'word_right' => 'かたわれ',
            'word_left' => '双子の',
            'get_method' => 'フルーツの楽園',
            'get_sentence' => '島にさくらんぼを植える',
          ],
          $words46 = [
            'word_sentence' => '食べごろの愛され者',
            'word_right' => '愛され者',
            'word_left' => '食べごろの',
            'get_method' => 'フルーツの楽園',
            'get_sentence' => '島にオレンジを植える',
          ],
          $words47 = [
            'word_sentence' => 'ナシよりのナシ',
            'word_right' => 'ナシ',
            'word_left' => 'ナシよりの',
            'get_method' => 'フルーツの楽園',
            'get_sentence' => '島にさくらんぼを植える',
            'get_sentence' => '島にナシを植える',
          ],
          $words48 = [
            'word_sentence' => 'フレッシュな人気者',
            'word_right' => '人気者',
            'word_left' => 'フレッシュな',
            'get_method' => 'フルーツの楽園',
            'get_sentence' => '島にさくらんぼを植える',
            'get_sentence' => '島にりんごを植える',
          ],
          $words49 = [
            'word_sentence' => 'からにこもった社会人',
            'word_right' => '社会人',
            'word_left' => 'からにこもった',
            'get_method' => '貝がら拾いの達人！',
            'get_sentence' => '貝がらを10回売る',
          ],
          $words50 = [
            'word_sentence' => '快活な会社員',
            'word_right' => '会社人',
            'word_left' => '快活な',
            'get_method' => '貝がら拾いの達人！',
            'get_sentence' => '貝がらを50回売る',
          ],
          $words51 = [
            'word_sentence' => 'おせっかいなギョーカイ人',
            'word_right' => 'ギョーカイ人',
            'word_left' => 'おせっかいな',
            'get_method' => '貝がら拾いの達人！',
            'get_sentence' => '貝がらを200回売る',
          ],
          $words52 = [
            'word_sentence' => '潮時の時期',
            'word_right' => '時期',
            'word_left' => '潮時の',
            'get_method' => '潮干狩りにチャレンジ！',
            'get_sentence' => '5回潮干狩りをする',
          ],
          $words53 = [
            'word_sentence' => 'アッサリ系の浜っ子',
            'word_right' => '浜っ子',
            'word_left' => 'アッサリ系の',
            'get_method' => '潮干狩りにチャレンジ！',
            'get_sentence' => '20回潮干狩りをする',
          ],
          $words54 = [
            'word_sentence' => '埋もれてる天才',
            'word_right' => '天才',
            'word_left' => '埋もれてる',
            'get_method' => '潮干狩りにチャレンジ！',
            'get_sentence' => '50回潮干狩りをする',
          ],
          $words55 = [
            'word_sentence' => '掘り出し物の逸材',
            'word_right' => '逸材',
            'word_left' => '掘り出し物の',
            'get_method' => '潮干狩りにチャレンジ！',
            'get_sentence' => '100回潮干狩りをする',
          ],
          $words56 = [
            'word_sentence' => '地球に優しいエコロジスト',
            'word_right' => 'エコロジスト',
            'word_left' => '地球に優しい',
            'get_method' => '海や川をキレイにしよう！',
            'get_sentence' => '10回美化活動に貢献する',
          ],
          $words57 = [
            'word_sentence' => 'もったいない廃棄物',
            'word_right' => '廃棄物',
            'word_left' => 'もったいない',
            'get_method' => '海や川をキレイにしよう！',
            'get_sentence' => '20回美化活動に貢献する',
          ],
          $words58 = [
            'word_sentence' => '外道のサカナ',
            'word_right' => 'サカナ',
            'word_left' => '外道の',
            'get_method' => '伝説の釣り人になれるかな？',
            'get_sentence' => '連続でサカナを10回釣る',
          ],
          $words59 = [
            'word_sentence' => '入れ食いのフィーバー中',
            'word_right' => 'フィーバー中',
            'word_left' => '入れ食いの',
            'get_method' => '伝説の釣り人になれるかな？',
            'get_sentence' => '20回美化活動に貢献する',
            'get_sentence' => '連続でサカナを50回釣る',
          ],
          $words60 = [
            'word_sentence' => 'ひとり暮らしの初心者',
            'word_right' => '初心者',
            'word_left' => 'ひとり暮らしの',
            'get_method' => '夢のマイホーム',
            'get_sentence' => '新築か増築を2回行う',
          ],
          $words61 = [
            'word_sentence' => '二階から管理人',
            'word_right' => '管理人',
            'word_left' => '二階から',
            'get_method' => '夢のマイホーム',
            'get_sentence' => '新築か増築を6回行う',
          ],
          $words62 = [
            'word_sentence' => 'ちょっぴりもようがえ好き',
            'word_right' => 'もようがえ好き',
            'word_left' => 'ちょっぴり',
            'get_method' => 'こだわりのインテリアで充実ライフ',
            'get_sentence' => '室内に15個家具を設置する',
          ],
          $words63 = [
            'word_sentence' => 'わりかし雑貨好き',
            'word_right' => '雑貨好き',
            'word_left' => 'わりかし',
            'get_method' => 'こだわりのインテリアで充実ライフ',
            'get_sentence' => '室内に30個家具を設置する',
          ],
          $words64 = [
            'word_sentence' => '余裕のないスタイリスト',
            'word_right' => 'スタイリスト',
            'word_left' => '余裕のない',
            'get_method' => '収納のプロは、暮らしのプロ',
            'get_sentence' => 'マイホームを建てて家の収納数を20個に増やす',
          ],
          $words65 = [
            'word_sentence' => '隠し切れていない才能',
            'word_right' => '才能',
            'word_left' => '隠し切れていない',
            'get_method' => '収納のプロは、暮らしのプロ',
            'get_sentence' => 'マイホームを増築して家の収納数を50個に増やす',
          ],
          $words66 = [
            'word_sentence' => '限界のマネージャー',
            'word_right' => 'マネージャー',
            'word_left' => '限界の',
            'get_method' => '収納のプロは、暮らしのプロ',
            'get_sentence' => 'マイホームを増築して家の収納数を100個に増やす',
          ],
          $words66 = [
            'word_sentence' => '持ってるコーディネーター',
            'word_right' => 'コーディネーター',
            'word_left' => '持ってる',
            'get_method' => '収納のプロは、暮らしのプロ',
            'get_sentence' => 'マイホームを増築して家の収納数を200個に増やす',
          ],
          $words67 = [
            'word_sentence' => '自宅のトランスフォーマー',
            'word_right' => 'トランスフォーマー',
            'word_left' => '自宅の',
            'get_method' => 'リフォームで心機一転！',
            'get_sentence' => 'リフォームを1回する',
          ],
          $words68 = [
            'word_sentence' => '親切な一般人',
            'word_right' => '一般人',
            'word_left' => '親切な',
            'get_method' => '親切は大切だなも！',
            'get_sentence' => '島民のお願いを1回きく',
          ],
          $words69 = [
            'word_sentence' => '頼れる味方',
            'word_right' => '味方',
            'word_left' => '頼れる',
            'get_method' => '親切は大切だなも！',
            'get_sentence' => '島民のお願いを50回きく',
          ],
          $words70 = [
            'word_sentence' => 'オーバーアクションな素人',
            'word_right' => '素人',
            'word_left' => 'オーバーアクションな',
            'get_method' => 'リアクションで充実コミュニケーション',
            'get_sentence' => 'リアクションを1つ覚える',
          ],
          $words71 = [
            'word_sentence' => '修行中ダンサー',
            'word_right' => 'ダンサー',
            'word_left' => '修行中',
            'get_method' => 'リアクションで充実コミュニケーション',
            'get_sentence' => 'リアクションを10つ覚える',
          ],
          $words72 = [
            'word_sentence' => 'ややウケのセミプロ',
            'word_right' => 'セミプロ',
            'word_left' => 'ややウケの',
            'get_method' => 'リアクションで充実コミュニケーション',
            'get_sentence' => 'リアクションを20つ覚える',
          ],
          $words73 = [
            'word_sentence' => 'ピンの芸人',
            'word_right' => '芸人',
            'word_left' => 'ピンの',
            'get_method' => 'リアクションで充実コミュニケーション',
            'get_sentence' => 'リアクションを30つ覚える',
          ],
          $words74 = [
            'word_sentence' => 'バえる写真好き',
            'word_right' => '写真好き',
            'word_left' => 'バえる',
            'get_method' => '思い出を写真に残そう',
            'get_sentence' => 'カメラアプリを使って写真を撮る',
          ],
          $words75 = [
            'word_sentence' => '未来の旅人',
            'word_right' => '旅人',
            'word_left' => '未来の',
            'get_method' => 'パスポートの更新もお忘れなく',
            'get_sentence' => 'パスポートの編集をする',
          ],
          $words76 = [
            'word_sentence' => 'スマホのユーザー',
            'word_right' => 'ユーザー',
            'word_left' => 'スマホの',
            'get_method' => 'スマホのある暮らし',
            'get_sentence' => 'スマホを使用する',
          ],
          $words77 = [
            'word_sentence' => 'デジタル社会の申し子',
            'word_right' => '申し子',
            'word_left' => 'デジタル社会の',
            'get_method' => 'スマホをフル活用！',
            'get_sentence' => 'スマホを200回使用する',
          ],
          $words78 = [
            'word_sentence' => 'インターネットのサーファー',
            'word_right' => 'サーファー',
            'word_left' => 'インターネットの',
            'get_method' => '通販ざんまい',
            'get_sentence' => 'たぬきショッピングを1回利用する',
          ],
          $words79 = [
            'word_sentence' => 'オンラインのレビュワー',
            'word_right' => 'レビュワー',
            'word_left' => 'オンラインの',
            'get_method' => '通販ざんまい',
            'get_sentence' => 'たぬきショッピングを20回利用する',
          ],
          $words80 = [
            'word_sentence' => 'ゆるい物欲',
            'word_right' => '物欲',
            'word_left' => 'ゆるい',
            'get_method' => 'カタログ充実で、毎日も充実♪',
            'get_sentence' => 'ごめんなさい！調査中です！',
          ],
          $words81 = [
            'word_sentence' => '物好きな一族',
            'word_right' => '一族',
            'word_left' => '物好きな',
            'get_method' => 'カタログ充実で、毎日も充実♪',
            'get_sentence' => 'ごめんなさい！調査中です！',
          ],
          $words82 = [
            'word_sentence' => '欲深いコレクター',
            'word_right' => 'コレクター',
            'word_left' => '欲深い',
            'get_method' => 'カタログ充実で、毎日も充実♪',
            'get_sentence' => 'ごめんなさい！調査中です！',
          ],
          $words83 = [
            'word_sentence' => 'コレクター化身',
            'word_right' => '化身',
            'word_left' => 'コレクター',
            'get_method' => 'カタログ充実で、毎日も充実♪',
            'get_sentence' => 'ごめんなさい！調査中です！',
          ],
          $words84 = [
            'word_sentence' => '伝説の生き字引',
            'word_right' => '生き字引',
            'word_left' => '伝説の',
            'get_method' => 'カタログ充実で、毎日も充実♪',
            'get_sentence' => 'ごめんなさい！調査中です！',
          ],
          $words85 = [
            'word_sentence' => 'いわゆる陸マイラー',
            'word_right' => '陸マイラー',
            'word_left' => 'いわゆる',
            'get_method' => 'マイレージ＋で マイルも＋',
            'get_sentence' => 'ごめんなさい！調査中です！',
          ],
          $words86 = [
            'word_sentence' => 'かけだしのルーキー',
            'word_right' => 'ルーキー',
            'word_left' => 'かけだしの',
            'get_method' => 'マイレージ＋で マイルも＋',
            'get_sentence' => 'ごめんなさい！調査中です！',
          ],
          $words87 = [
            'word_sentence' => '一人前の消費者',
            'word_right' => '消費者',
            'word_left' => '一人前の',
            'get_method' => 'お買い求め、ありがとうございます！',
            'get_sentence' => '島ではじめて買い物をする',
          ],
          $words88 = [
            'word_sentence' => '金欠の予備軍',
            'word_right' => '予備軍',
            'word_left' => '金欠の',
            'get_method' => '不用品、買い取ります！',
            'get_sentence' => 'はじめて買取サービスをつかう',
          ],
          $words89 = [
            'word_sentence' => '自由な生活',
            'word_right' => '生活',
            'word_left' => '自由な',
            'get_method' => '移住費用マイルパック！',
            'get_sentence' => '無人島移住費用を支払う',
          ],
          $words90 = [
            'word_sentence' => 'コスパ重視の買い物好き',
            'word_right' => '買い物好き',
            'word_left' => 'コスパ重視の',
            'get_method' => 'ショッピングで経済循環だなも',
            'get_sentence' => '買い物で5000ベル使用する',
          ],
          $words91 = [
            'word_sentence' => '節約家のファミリー',
            'word_right' => 'ファミリー',
            'word_left' => '節約家の',
            'get_method' => 'ショッピングで経済循環だなも',
            'get_sentence' => '買い物で50000ベル使用する',
          ],
          $words92 = [
            'word_sentence' => '貪欲な性格',
            'word_right' => '性格',
            'word_left' => '貪欲な',
            'get_method' => 'ショッピングで経済循環だなも',
            'get_sentence' => '買い物で500000ベル使用する',
          ],
          $words92 = [
            'word_sentence' => '浪費家のセレブ',
            'word_right' => 'セレブ',
            'word_left' => '浪費家の',
            'get_method' => 'ショッピングで経済循環だなも',
            'get_sentence' => '買い物で2000000ベル使用する',
          ],
          $words93 = [
            'word_sentence' => '週末のカブ主',
            'word_right' => 'カブ主',
            'word_left' => '週末の',
            'get_method' => 'カブ主様へ、ご優待マイル',
            'get_sentence' => 'カブを買う',
          ],
          $words94 = [
            'word_sentence' => '様子見中のギャンブラー',
            'word_right' => 'ギャンブラー',
            'word_left' => '様子見中の',
            'get_method' => 'カブ・ドリーマーへの道',
            'get_sentence' => 'カブで1,000ベルの利益を出す',
          ],
          $words95 = [
            'word_sentence' => '金欲の小金持ち',
            'word_right' => '小金持ち',
            'word_left' => '金欲の',
            'get_method' => 'カブ・ドリーマーへの道',
            'get_sentence' => 'カブで10,000ベルの利益を出す',
          ],
          $words96 = [
            'word_sentence' => '成金のトレーダー',
            'word_right' => 'トレーダー',
            'word_left' => '成金の',
            'get_method' => 'カブ・ドリーマーへの道',
            'get_sentence' => 'カブで100,000ベルの利益を出す',
          ],
          $words97 = [
            'word_sentence' => '世界のミリオネア',
            'word_right' => 'ミリオネア',
            'word_left' => '世界の',
            'get_method' => 'カブ・ドリーマーへの道',
            'get_sentence' => 'カブで1,000,000ベルの利益を出す',
          ],
          $words98 = [
            'word_sentence' => 'ローンの卒業生',
            'word_right' => '卒業生',
            'word_left' => 'ローンの',
            'get_method' => '祝！ローン完済だなも！',
            'get_sentence' => '家のローンを完済する',
          ],
          $words99 = [
            'word_sentence' => 'うわさ好きなインフルエンサー',
            'word_right' => 'インフルエンサー',
            'word_left' => 'うわさ好きな',
            'get_method' => '掲示板でコミュニケーション',
            'get_sentence' => '初めて島の掲示板に書き込みをする',
          ],
          $words100 = [
            'word_sentence' => '文系の女子（男子）',
            'word_right' => '女子（男子）',
            'word_left' => '文系の',
            'get_method' => '掲示板でコミュニケーション',
            'get_sentence' => '	メッセージカードを5枚送る',
          ],
          $words101 = [
            'word_sentence' => 'キレイ好きなチルドレン',
            'word_right' => 'チルドレン',
            'word_left' => 'キレイ好きな',
            'get_method' => 'ノミをつかまえよう！',
            'get_sentence' => 'ノミを1匹捕まえる',
          ],
          $words102 = [
            'word_sentence' => '意識の高い綺麗好き',
            'word_right' => '綺麗好き',
            'word_left' => '意識の高い',
            'get_method' => 'ノミをつかまえよう！',
            'get_sentence' => 'ノミを5匹捕まえる',
          ],
          $words102 = [
            'word_sentence' => '清潔なキャラ',
            'word_right' => 'キャラ',
            'word_left' => '清潔な',
            'get_method' => 'ノミをつかまえよう！',
            'get_sentence' => 'ノミを10匹捕まえる',
          ],
          $words103 = [
            'word_sentence' => '抜け殻の存在',
            'word_right' => '存在',
            'word_left' => '抜け殻の',
            'get_method' => '夏の思い出ゲット！',
            'get_sentence' => 'セミの抜け殻を入手する',
          ],
          $words104 = [
            'word_sentence' => 'ハズさないスナイパー',
            'word_right' => 'スナイパー',
            'word_left' => 'ハズさない',
            'get_method' => 'ハチとり名人！',
            'get_sentence' => '1日に連続5回ハチを捕まえる',
          ],
          $words105 = [
            'word_sentence' => 'ちょいワルのトラブルメイカー',
            'word_right' => 'トラブルメイカー',
            'word_left' => 'ちょいワルの',
            'get_method' => 'わるだくみ番長！',
            'get_sentence' => '落とし穴をDIYする',
          ],
          $words106 = [
            'word_sentence' => '泣きっ面の泣き虫',
            'word_right' => '泣き虫',
            'word_left' => '泣きっ面の',
            'get_method' => '泣きっ面にハチの救済なんだも！',
            'get_sentence' => 'ハチにさされた状態でハチにさされる',
          ],
          $words107 = [
            'word_sentence' => '蘇った不死鳥',
            'word_right' => '不死鳥',
            'word_left' => '蘇った',
            'get_method' => 'キケンなムシに、ご注意',
            'get_sentence' => 'タランチュラをつかまえる',
          ],
          $words108 = [
            'word_sentence' => 'ワナにはまったうっかり者',
            'word_right' => 'うっかり者',
            'word_left' => 'ワナにはまった',
            'get_method' => '落とし穴のワナだなも！',
            'get_sentence' => '落とし穴に落ちる',
          ],
          $words109 = [
            'word_sentence' => '水もしたたるドジっ子',
            'word_right' => 'ドジっ子',
            'word_left' => '水もしたたる',
            'get_method' => 'ウォーターハザード',
            'get_sentence' => '風船を水の中に落とす',
          ],
          $words110 = [
            'word_sentence' => 'ゆるふわ系のパチンカー',
            'word_right' => 'パチンカー',
            'word_left' => 'ゆるふわ系の',
            'get_method' => '狙え、バルーンハンター！',
            'get_sentence' => '風船を5回撃ち落とす',
          ],
          $words111 = [
            'word_sentence' => 'フワッとしてる空気',
            'word_right' => '空気',
            'word_left' => 'フワッとしてる',
            'get_method' => '狙え、バルーンハンター！',
            'get_sentence' => '風船を20回撃ち落とす',
          ],
          $words112 = [
            'word_sentence' => '浮き足立つハンター',
            'word_right' => 'ハンター',
            'word_left' => '浮き足立つ',
            'get_method' => '狙え、バルーンハンター！',
            'get_sentence' => '風船を50回撃ち落とす',
          ],
          $words112 = [
            'word_sentence' => 'ぶっとんでいるパラダイス',
            'word_right' => 'パラダイス',
            'word_left' => 'ぶっとんでいる',
            'get_method' => '狙え、バルーンハンター！',
            'get_sentence' => '風船を100回撃ち落とす',
          ],
          $words113 = [
            'word_sentence' => '神出鬼没の風来坊',
            'word_right' => '風来坊',
            'word_left' => '神出鬼没の',
            'get_method' => '狙え、バルーンハンター！',
            'get_sentence' => '風船を300回撃ち落とす',
          ],
          $words114 = [
            'word_sentence' => 'サクっと仕切り屋',
            'word_right' => '仕切り屋',
            'word_left' => 'サクっと',
            'get_method' => '柵でお庭を作りませんか？',
            'get_sentence' => '柵を20個建てる',
          ],
        ];
        foreach ($words as $word) {
        DB::table('words')->insert($word);
        }
    }
}
